//AUTOGENERATED FILE FROM png2asset
#ifndef METASPRITE_splash_laurels_1k_map_H
#define METASPRITE_splash_laurels_1k_map_H

#include <stdint.h>
#include <gbdk/platform.h>
#include <gbdk/metasprites.h>

#define splash_laurels_1k_map_TILE_ORIGIN 0
#define splash_laurels_1k_map_TILE_W 8
#define splash_laurels_1k_map_TILE_H 8
#define splash_laurels_1k_map_WIDTH 160
#define splash_laurels_1k_map_HEIGHT 144
#define splash_laurels_1k_map_TILE_COUNT 121
#define splash_laurels_1k_map_MAP_ATTRIBUTES 0
extern const unsigned char splash_laurels_1k_map_map[360];
#define splash_laurels_1k_map_map_attributes splash_laurels_1k_map_map

BANKREF_EXTERN(splash_laurels_1k_map)


#endif
