//AUTOGENERATED FILE FROM png2asset
#ifndef METASPRITE_splash_laurels_1k_tiles_H
#define METASPRITE_splash_laurels_1k_tiles_H

#include <stdint.h>
#include <gbdk/platform.h>
#include <gbdk/metasprites.h>

#define splash_laurels_1k_tiles_TILE_ORIGIN 0
#define splash_laurels_1k_tiles_TILE_W 8
#define splash_laurels_1k_tiles_TILE_H 8
#define splash_laurels_1k_tiles_WIDTH 160
#define splash_laurels_1k_tiles_HEIGHT 144
#define splash_laurels_1k_tiles_TILE_COUNT 121

BANKREF_EXTERN(splash_laurels_1k_tiles)

extern const uint8_t splash_laurels_1k_tiles_tiles[1936];

#endif
